name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main          # Production deployment
      - staging       # Staging deployment

jobs:
  # Staging Environment (staging branch)
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: staging
      lambda-function-name: ${{ secrets.LAMBDA_FUNCTION_NAME_STAGING }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      aws-region: ${{ secrets.AWS_REGION }}
      node-env: staging
      require-tests: false
      s3-bucket: ${{ secrets.S3_BUCKET_NAME }}

  # Production Environment (main branch)
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: production
      lambda-function-name: ${{ secrets.LAMBDA_FUNCTION_NAME_PROD }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      aws-region: ${{ secrets.AWS_REGION }}
      node-env: production
      require-tests: true
      s3-bucket: ${{ secrets.S3_BUCKET_NAME }}
